services:
  mysql:
    image: mysql:latest
    container_name: reeserve-mysql
    networks:
      - reeserve-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - 3306:3306
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-container
    networks:
      - reeserve-network
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
  redis:
    image: redis:latest
    container_name: reeserve-redis
    networks:
      - reeserve-network
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:

networks:
  reeserve-network:
    name: reeserve-network
    driver: bridge
