services:
  mysql:
    image: mysql:latest
    container_name: reeserve-mysql
    networks:
      - reeserve-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - 3306:3306
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  reeserve-network:
    name: reeserve-network
    driver: bridge
